<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIg9GRdo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIg9GRdo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIg9GRdo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIg9GRdo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIg9GRdo\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ig9GRdo',
    'container.build_id' => '243a764c',
    'container.build_time' => 1734436450,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIg9GRdo');
