<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_lucky_number' => [[], ['_controller' => 'App\\Controller\\LuckyController::number'], [], [['text', '/lucky/number']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\RoleController::index'], [], [['text', '/api/roles']], [], [], []],
    'list' => [[], ['_controller' => 'App\\Controller\\UsersController::index'], [], [['text', '/api/users']], [], [], []],
    'show' => [['id'], ['_controller' => 'App\\Controller\\UsersController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'create' => [[], ['_controller' => 'App\\Controller\\UsersController::create'], [], [['text', '/api/users']], [], [], []],
    'update' => [['id'], ['_controller' => 'App\\Controller\\UsersController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'delete' => [['id'], ['_controller' => 'App\\Controller\\UsersController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'App\Controller\GenderController::index' => [[], ['_controller' => 'App\\Controller\\RoleController::index'], [], [['text', '/api/roles']], [], [], []],
    'App\Controller\GenderController::create' => [[], ['_controller' => 'App\\Controller\\UsersController::create'], [], [['text', '/api/users']], [], [], []],
    'App\Controller\GenderController::show' => [['id'], ['_controller' => 'App\\Controller\\UsersController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'App\Controller\GenderController::update' => [['id'], ['_controller' => 'App\\Controller\\UsersController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'App\Controller\GenderController::delete' => [['id'], ['_controller' => 'App\\Controller\\UsersController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'App\Controller\LuckyController::number' => [[], ['_controller' => 'App\\Controller\\LuckyController::number'], [], [['text', '/lucky/number']], [], [], []],
    'App\Controller\RoleController::index' => [[], ['_controller' => 'App\\Controller\\RoleController::index'], [], [['text', '/api/roles']], [], [], []],
    'App\Controller\RoleController::create' => [[], ['_controller' => 'App\\Controller\\UsersController::create'], [], [['text', '/api/users']], [], [], []],
    'App\Controller\RoleController::show' => [['id'], ['_controller' => 'App\\Controller\\UsersController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'App\Controller\RoleController::update' => [['id'], ['_controller' => 'App\\Controller\\UsersController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'App\Controller\RoleController::delete' => [['id'], ['_controller' => 'App\\Controller\\UsersController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'App\Controller\UsersController::index' => [[], ['_controller' => 'App\\Controller\\UsersController::index'], [], [['text', '/api/users']], [], [], []],
    'App\Controller\UsersController::show' => [['id'], ['_controller' => 'App\\Controller\\UsersController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'App\Controller\UsersController::create' => [[], ['_controller' => 'App\\Controller\\UsersController::create'], [], [['text', '/api/users']], [], [], []],
    'App\Controller\UsersController::update' => [['id'], ['_controller' => 'App\\Controller\\UsersController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
    'App\Controller\UsersController::delete' => [['id'], ['_controller' => 'App\\Controller\\UsersController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/users']], [], [], []],
];
