services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_projet_cloud_S5
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      MAILER_DSN: 'smtp://mailhog:1025'
    command: php -S 0.0.0.0:8000 -t public
    depends_on:
      - db
      - mailhog

  db:
    image: postgres:15
    container_name: symfony_db_projet_cloud_S5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cloud
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    container_name: symfony_mailhog
    ports:
      - "1025:1025" 
      - "8025:8025" 