<?php

namespace ContainerAqD86ZB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PQWV7E6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pQWV7E6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pQWV7E6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\GenderController::index' => ['privates', '.service_locator.aeUASzz.App\\Controller\\GenderController::index()', 'getGenderControllerindexService', true],
            'App\\Controller\\GenderController::show' => ['privates', '.service_locator.aeUASzz.App\\Controller\\GenderController::show()', 'getGenderControllershowService', true],
            'App\\Controller\\GenderController::update' => ['privates', '.service_locator.aeUASzz.App\\Controller\\GenderController::update()', 'getGenderControllerupdateService', true],
            'App\\Controller\\GenderController::delete' => ['privates', '.service_locator.aeUASzz.App\\Controller\\GenderController::delete()', 'getGenderControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.4wc4Ag1.kernel::registerContainerConfiguration()', 'get_ServiceLocator_4wc4Ag1_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.4wc4Ag1.kernel::loadRoutes()', 'get_ServiceLocator_4wc4Ag1_KernelloadRoutesService', true],
            'App\\Controller\\GenderController:index' => ['privates', '.service_locator.aeUASzz.App\\Controller\\GenderController::index()', 'getGenderControllerindexService', true],
            'App\\Controller\\GenderController:show' => ['privates', '.service_locator.aeUASzz.App\\Controller\\GenderController::show()', 'getGenderControllershowService', true],
            'App\\Controller\\GenderController:update' => ['privates', '.service_locator.aeUASzz.App\\Controller\\GenderController::update()', 'getGenderControllerupdateService', true],
            'App\\Controller\\GenderController:delete' => ['privates', '.service_locator.aeUASzz.App\\Controller\\GenderController::delete()', 'getGenderControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\GenderController::index' => '?',
            'App\\Controller\\GenderController::show' => '?',
            'App\\Controller\\GenderController::update' => '?',
            'App\\Controller\\GenderController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\GenderController:index' => '?',
            'App\\Controller\\GenderController:show' => '?',
            'App\\Controller\\GenderController:update' => '?',
            'App\\Controller\\GenderController:delete' => '?',
        ]);
    }
}
