<?php

namespace ContainerAqD86ZB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenderControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aeUASzz.App\Controller\GenderController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aeUASzz.App\\Controller\\GenderController::delete()'] = ($container->privates['.service_locator.aeUASzz'] ?? $container->load('get_ServiceLocator_AeUASzzService'))->withContext('App\\Controller\\GenderController::delete()', $container);
    }
}
